/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author ASUS
 */
public class BiodataSiswa extends javax.swing.JFrame {

    /**
     * Creates new form BiodataSiswa
     */
    public BiodataSiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nama = new javax.swing.JTextField();
        absen = new javax.swing.JTextField();
        kelas = new javax.swing.JComboBox<>();
        jurusanrpl = new javax.swing.JRadioButton();
        jurusantkj = new javax.swing.JRadioButton();
        alamat = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Biodata Siswa");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 20, 139, 41);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 80, 90, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Absen");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 130, 50, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Kelas");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 190, 60, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Jurusan");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 250, 50, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Alamat");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 310, 50, 17);
        jPanel1.add(nama);
        nama.setBounds(110, 70, 290, 40);
        jPanel1.add(absen);
        absen.setBounds(110, 120, 290, 40);

        kelas.setForeground(new java.awt.Color(204, 204, 204));
        kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X RPL 1 ", "X RPL 2", "X RPL 3", "X RPL 4", "X RPL 5", "X RPL 6", "X RPL 7", "X TKJ 1", "X TKJ 2", "X TKJ 3", "X TKJ 4", "X TKJ 5", "X TKJ 6", " " }));
        kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasActionPerformed(evt);
            }
        });
        jPanel1.add(kelas);
        kelas.setBounds(110, 180, 140, 40);

        buttonGroup1.add(jurusanrpl);
        jurusanrpl.setForeground(new java.awt.Color(204, 204, 204));
        jurusanrpl.setText("RPL");
        jPanel1.add(jurusanrpl);
        jurusanrpl.setBounds(110, 240, 80, 40);

        buttonGroup1.add(jurusantkj);
        jurusantkj.setForeground(new java.awt.Color(204, 204, 204));
        jurusantkj.setText("TKJ");
        jurusantkj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusantkjActionPerformed(evt);
            }
        });
        jPanel1.add(jurusantkj);
        jurusantkj.setBounds(250, 240, 90, 40);
        jPanel1.add(alamat);
        alamat.setBounds(110, 310, 340, 90);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(430, 160, 70, 23);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(430, 210, 70, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 620, 450);

        setBounds(0, 0, 619, 486);
    }// </editor-fold>//GEN-END:initComponents

    private void kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kelasActionPerformed

    private void jurusantkjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusantkjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jurusantkjActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String name = nama.getText();
     String absent = absen.getText();
     String kelab =kelas.getSelectedItem().toString();
     String jurusan =" ";
     String omah = alamat.getText();
     if (jurusanrpl.isSelected()) {
         jurusan = "RPL";}
     else if (jurusantkj.isSelected()){
                jurusan ="TKJ";    
     if (kelas.getSelectedItem()=="X RPL 1");{
     }
     if (kelas.getSelectedItem()=="X RPL 2");{
     }
     
     if (kelas.getSelectedItem()=="X RPL 3");{
         
     }
     if (kelas.getSelectedItem()=="X RPL 4");{
         
     }
      if (kelas.getSelectedItem()=="X RPL 5");{
         
     }
       if (kelas.getSelectedItem()=="X RPL 6");{
         
     }
      if (kelas.getSelectedItem()=="X RPL 7");
     }{{
    
                        
      if (kelas.getSelectedItem()=="X TKJ 1");{
     }
     if (kelas.getSelectedItem()=="X TKJ 2");{
     }
     
     if (kelas.getSelectedItem()=="X TKJ 3");{
         
     }
     if (kelas.getSelectedItem()=="X TKJ 4");{
         
     }
      if (kelas.getSelectedItem()=="X TKJ 5");{
         
     }
       if (kelas.getSelectedItem()=="X TKJ 6");{
         }
     }
      
  new Frame2 (name,absent,kelab,jurusan,omah).setVisible(true);}  
    }//GEN-LAST:event_jButton1ActionPerformed
   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
          /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField absen;
    private javax.swing.JTextField alamat;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jurusanrpl;
    private javax.swing.JRadioButton jurusantkj;
    private javax.swing.JComboBox<String> kelas;
    private javax.swing.JTextField nama;
    // End of variables declaration//GEN-END:variables
}
