/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;
/**
 *
 * @author ASUS
 */
public class KalkulatorStandard extends javax.swing.JFrame {
 String bil="";
 double bilsatu = -1.0;
double jumlah,bilangan1,bilangan2;
int pilih;
    /**
     * Creates new form KalkulatorStandard
     */
    public KalkulatorStandard() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        hapus1 = new javax.swing.JButton();
        bil7 = new javax.swing.JButton();
        bil4 = new javax.swing.JButton();
        bil1 = new javax.swing.JButton();
        modulus = new javax.swing.JButton();
        bil8 = new javax.swing.JButton();
        bil5 = new javax.swing.JButton();
        bil2 = new javax.swing.JButton();
        bil0 = new javax.swing.JButton();
        hapus3 = new javax.swing.JButton();
        bil9 = new javax.swing.JButton();
        bil6 = new javax.swing.JButton();
        bil3 = new javax.swing.JButton();
        titik = new javax.swing.JButton();
        plusmin = new javax.swing.JButton();
        bagi = new javax.swing.JButton();
        kali = new javax.swing.JButton();
        kurang = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        akarpangkat = new javax.swing.JButton();
        sisahasilbagi = new javax.swing.JButton();
        pangkat = new javax.swing.JButton();
        hasil = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kalkulator KrisnaPM");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(java.awt.Color.darkGray);
        jPanel1.setForeground(new java.awt.Color(204, 204, 204));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        display.setEditable(false);
        display.setBackground(java.awt.Color.darkGray);
        display.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        display.setForeground(new java.awt.Color(204, 204, 204));
        display.setText("  ");
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });
        jPanel1.add(display);
        display.setBounds(10, 20, 380, 90);

        hapus1.setBackground(java.awt.Color.darkGray);
        hapus1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hapus1.setForeground(new java.awt.Color(255, 255, 255));
        hapus1.setText("←");
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });
        jPanel1.add(hapus1);
        hapus1.setBounds(10, 140, 60, 40);

        bil7.setBackground(java.awt.Color.darkGray);
        bil7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bil7.setForeground(new java.awt.Color(255, 255, 255));
        bil7.setText("7");
        bil7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil7ActionPerformed(evt);
            }
        });
        jPanel1.add(bil7);
        bil7.setBounds(10, 190, 60, 40);

        bil4.setBackground(java.awt.Color.darkGray);
        bil4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bil4.setForeground(new java.awt.Color(255, 255, 255));
        bil4.setText("4");
        bil4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil4ActionPerformed(evt);
            }
        });
        jPanel1.add(bil4);
        bil4.setBounds(10, 240, 60, 40);

        bil1.setBackground(java.awt.Color.darkGray);
        bil1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bil1.setForeground(new java.awt.Color(255, 255, 255));
        bil1.setText("1");
        bil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil1ActionPerformed(evt);
            }
        });
        jPanel1.add(bil1);
        bil1.setBounds(10, 290, 60, 40);

        modulus.setBackground(java.awt.Color.darkGray);
        modulus.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        modulus.setForeground(new java.awt.Color(255, 255, 255));
        modulus.setText("%");
        modulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulusActionPerformed(evt);
            }
        });
        jPanel1.add(modulus);
        modulus.setBounds(330, 190, 60, 40);

        bil8.setBackground(java.awt.Color.darkGray);
        bil8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bil8.setForeground(new java.awt.Color(255, 255, 255));
        bil8.setText("8");
        bil8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil8ActionPerformed(evt);
            }
        });
        jPanel1.add(bil8);
        bil8.setBounds(90, 190, 60, 40);

        bil5.setBackground(java.awt.Color.darkGray);
        bil5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bil5.setForeground(new java.awt.Color(255, 255, 255));
        bil5.setText("5");
        bil5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil5ActionPerformed(evt);
            }
        });
        jPanel1.add(bil5);
        bil5.setBounds(90, 240, 60, 40);

        bil2.setBackground(java.awt.Color.darkGray);
        bil2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bil2.setForeground(new java.awt.Color(255, 255, 255));
        bil2.setText("2");
        bil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil2ActionPerformed(evt);
            }
        });
        jPanel1.add(bil2);
        bil2.setBounds(90, 290, 60, 40);

        bil0.setBackground(java.awt.Color.darkGray);
        bil0.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bil0.setForeground(new java.awt.Color(255, 255, 255));
        bil0.setText("0");
        bil0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil0ActionPerformed(evt);
            }
        });
        jPanel1.add(bil0);
        bil0.setBounds(10, 340, 130, 40);

        hapus3.setBackground(java.awt.Color.darkGray);
        hapus3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hapus3.setForeground(new java.awt.Color(255, 255, 255));
        hapus3.setText("C");
        hapus3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus3ActionPerformed(evt);
            }
        });
        jPanel1.add(hapus3);
        hapus3.setBounds(170, 140, 60, 40);

        bil9.setBackground(java.awt.Color.darkGray);
        bil9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bil9.setForeground(new java.awt.Color(255, 255, 255));
        bil9.setText("9");
        bil9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil9ActionPerformed(evt);
            }
        });
        jPanel1.add(bil9);
        bil9.setBounds(170, 190, 60, 40);

        bil6.setBackground(java.awt.Color.darkGray);
        bil6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bil6.setForeground(new java.awt.Color(255, 255, 255));
        bil6.setText("6");
        bil6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil6ActionPerformed(evt);
            }
        });
        jPanel1.add(bil6);
        bil6.setBounds(170, 240, 60, 40);

        bil3.setBackground(java.awt.Color.darkGray);
        bil3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bil3.setForeground(new java.awt.Color(255, 255, 255));
        bil3.setText("3");
        bil3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bil3ActionPerformed(evt);
            }
        });
        jPanel1.add(bil3);
        bil3.setBounds(170, 290, 60, 40);

        titik.setBackground(java.awt.Color.darkGray);
        titik.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titik.setForeground(new java.awt.Color(255, 255, 255));
        titik.setText(".");
        titik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titikActionPerformed(evt);
            }
        });
        jPanel1.add(titik);
        titik.setBounds(170, 340, 60, 40);

        plusmin.setBackground(java.awt.Color.darkGray);
        plusmin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        plusmin.setForeground(new java.awt.Color(255, 255, 255));
        plusmin.setText("±");
        plusmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusminActionPerformed(evt);
            }
        });
        jPanel1.add(plusmin);
        plusmin.setBounds(250, 140, 60, 40);

        bagi.setBackground(java.awt.Color.darkGray);
        bagi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        bagi.setForeground(new java.awt.Color(255, 255, 255));
        bagi.setText("/");
        bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagiActionPerformed(evt);
            }
        });
        jPanel1.add(bagi);
        bagi.setBounds(250, 190, 60, 40);

        kali.setBackground(java.awt.Color.darkGray);
        kali.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kali.setForeground(new java.awt.Color(255, 255, 255));
        kali.setText("×࣯");
        kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaliActionPerformed(evt);
            }
        });
        jPanel1.add(kali);
        kali.setBounds(250, 240, 60, 40);

        kurang.setBackground(java.awt.Color.darkGray);
        kurang.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        kurang.setForeground(new java.awt.Color(255, 255, 255));
        kurang.setText("-");
        kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurangActionPerformed(evt);
            }
        });
        jPanel1.add(kurang);
        kurang.setBounds(250, 290, 60, 40);

        tambah.setBackground(java.awt.Color.darkGray);
        tambah.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        tambah.setForeground(new java.awt.Color(255, 255, 255));
        tambah.setText("+");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah);
        tambah.setBounds(250, 340, 60, 40);

        akarpangkat.setBackground(java.awt.Color.darkGray);
        akarpangkat.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        akarpangkat.setForeground(new java.awt.Color(255, 255, 255));
        akarpangkat.setText("√");
        akarpangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akarpangkatActionPerformed(evt);
            }
        });
        jPanel1.add(akarpangkat);
        akarpangkat.setBounds(330, 140, 60, 40);

        sisahasilbagi.setBackground(java.awt.Color.darkGray);
        sisahasilbagi.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        sisahasilbagi.setForeground(new java.awt.Color(255, 255, 255));
        sisahasilbagi.setText("MOD");
        sisahasilbagi.setBorder(null);
        sisahasilbagi.setBorderPainted(false);
        sisahasilbagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sisahasilbagiActionPerformed(evt);
            }
        });
        jPanel1.add(sisahasilbagi);
        sisahasilbagi.setBounds(80, 140, 80, 40);

        pangkat.setBackground(java.awt.Color.darkGray);
        pangkat.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        pangkat.setForeground(new java.awt.Color(255, 255, 255));
        pangkat.setText("^");
        pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pangkatActionPerformed(evt);
            }
        });
        jPanel1.add(pangkat);
        pangkat.setBounds(330, 240, 60, 40);

        hasil.setBackground(java.awt.Color.darkGray);
        hasil.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        hasil.setForeground(new java.awt.Color(255, 255, 255));
        hasil.setText("=");
        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        jPanel1.add(hasil);
        hasil.setBounds(330, 290, 60, 90);

        jLabel2.setBackground(java.awt.Color.darkGray);
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Pictures\\Dark red cool 1.jpg")); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -20, 400, 460);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 400);

        setBounds(0, 0, 416, 439);
    }// </editor-fold>//GEN-END:initComponents

    private void bil6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil6ActionPerformed
        // TODO add your handling code here:
       bil += "6";
       display.setText(bil);
        
    }//GEN-LAST:event_bil6ActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        bilangan1=Double.parseDouble(bil);
display.setText("+");
bil="";
pilih=1;
    }//GEN-LAST:event_tambahActionPerformed

    private void bil7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil7ActionPerformed
        // TODO add your handling code here:
      bil += "7";
       display.setText(bil);
    }//GEN-LAST:event_bil7ActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        
    }//GEN-LAST:event_displayActionPerformed

    private void bil8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil8ActionPerformed
        // TODO add your handling code here:
         bil += "8";
       display.setText(bil);
    }//GEN-LAST:event_bil8ActionPerformed

    private void bil9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil9ActionPerformed
        // TODO add your handling code here:
         bil += "9";
       display.setText(bil);
    }//GEN-LAST:event_bil9ActionPerformed

    private void bil5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil5ActionPerformed
 bil += "5";
       display.setText(bil);        // TODO add your handling code here:
    }//GEN-LAST:event_bil5ActionPerformed

    private void bil4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil4ActionPerformed
        // TODO add your handling code here:
         bil += "4";
       display.setText(bil);
    }//GEN-LAST:event_bil4ActionPerformed

    private void bil1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil1ActionPerformed
        // TODO add your handling code here:
         bil += "1";
       display.setText(bil);
    }//GEN-LAST:event_bil1ActionPerformed

    private void bil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil2ActionPerformed
        // TODO add your handling code here:
         bil += "2";
       display.setText(bil);
    }//GEN-LAST:event_bil2ActionPerformed

    private void bil3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil3ActionPerformed
        // TODO add your handling code here:
         bil += "3";
       display.setText(bil);
    }//GEN-LAST:event_bil3ActionPerformed

    private void bil0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bil0ActionPerformed
        // TODO add your handling code here:
         bil += "0";
       display.setText(bil);
    }//GEN-LAST:event_bil0ActionPerformed

    private void titikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titikActionPerformed
        // TODO add your handling code here:
        bil += ".";
display.setText(bil);
    }//GEN-LAST:event_titikActionPerformed

    private void hapus3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus3ActionPerformed
        // TODO add your handling code here:display.setText("");
bilangan1=0.0;
bilangan2=0.0;
jumlah=0.0;
bil="";
display.setText("0");

    }//GEN-LAST:event_hapus3ActionPerformed

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        // TODO add your handling code here:
      display.getText().length();
StringBuilder all = new StringBuilder (display.getText());
char end = all.charAt(all.length()-1);
all.deleteCharAt(all.length()-1);
display.setText(all.toString());
bil = display.getText();
   if (display.getText().length() == 0){
       display.setText("0");
    hapus1.setEnabled(true);
    titik.setEnabled(true);
    bagi.setEnabled(true);
    kali.setEnabled(true);
    tambah.setEnabled(true);   
    }//GEN-LAST:event_hapus1ActionPerformed
    }
    private void modulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulusActionPerformed
        // TODO add your handling code here:
         bilangan1=Double.parseDouble(bil);
jumlah = bilangan1 *1 / 100;
            bil = Double.toString(jumlah);
            
            display.setText(bil);
    }//GEN-LAST:event_modulusActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
        switch(pilih){
        case 1:
            bilangan2 = Double.parseDouble(bil);
            jumlah = bilangan1 + bilangan2;
            bil = Double.toString(jumlah);
            display.setText(bil);
            break;
        case 2:
           bilangan2=Double.parseDouble(bil);
            jumlah = bilangan1 / bilangan2;
            bil = Double.toString(jumlah);
            display.setText(bil);
            break;
        case 3:
            bilangan2 = Double.parseDouble(bil);
            jumlah = bilangan1 * bilangan2;
            bil = Double.toString(jumlah);
            display.setText(bil);
            break;
         case 4:
            bilangan2 = Double.parseDouble(bil);
            jumlah = bilangan1 - bilangan2;
            bil = Double.toString(jumlah);
            display.setText(bil);
            break;
        case 5:
            bilangan2 = Double.parseDouble(bil);
            jumlah = bilangan1 % bilangan2;
            bil = Double.toString(jumlah);
            display.setText(bil);
            break;
        case 6:
            bilangan2 = Double.parseDouble(bil);
            jumlah = Math.pow(bilangan1, bilangan2);
            bil = Double.toString(jumlah);
            display.setText(bil);
            break;
       
                
        }
    }//GEN-LAST:event_hasilActionPerformed

    private void bagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagiActionPerformed
        // TODO add your handling code here:
         bilangan1=Double.parseDouble(bil);
display.setText("/");
bil="";
pilih=2;
    }//GEN-LAST:event_bagiActionPerformed

    private void kaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaliActionPerformed
        // TODO add your handling code here:
         bilangan1=Double.parseDouble(bil);
display.setText("X");
bil="";
pilih=3;
    }//GEN-LAST:event_kaliActionPerformed

    private void kurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurangActionPerformed
        // TODO add your handling code here:
         bilangan1=Double.parseDouble(bil);
 display.setText("-");
bil="";
pilih=4;
    }//GEN-LAST:event_kurangActionPerformed

    private void sisahasilbagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sisahasilbagiActionPerformed
        // TODO add your handling code here:
         bilangan1=Double.parseDouble(bil);
display.setText("%");
bil="";
pilih=5;
    }//GEN-LAST:event_sisahasilbagiActionPerformed

    private void pangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pangkatActionPerformed
        // TODO add your handling code here:
         bilangan1=Double.parseDouble(bil);
display.setText("^");
bil="";
pilih=6;
    }//GEN-LAST:event_pangkatActionPerformed

    private void akarpangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akarpangkatActionPerformed
        // TODO add your handling code here:
         bilangan1=Double.parseDouble(bil);
  bilangan2 = 2.0;
            jumlah = Math.sqrt(bilangan1);
            bil = Double.toString(jumlah);
            display.setText(bil);
    }//GEN-LAST:event_akarpangkatActionPerformed

    private void plusminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusminActionPerformed
        // TODO add your handling code here:
         bilangan1=Double.parseDouble(bil);
jumlah = bilangan1 * bilsatu;
bil=Double.toString(jumlah);
display.setText(bil);
pilih=8;
    }//GEN-LAST:event_plusminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorStandard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorStandard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorStandard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorStandard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorStandard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton akarpangkat;
    private javax.swing.JButton bagi;
    private javax.swing.JButton bil0;
    private javax.swing.JButton bil1;
    private javax.swing.JButton bil2;
    private javax.swing.JButton bil3;
    private javax.swing.JButton bil4;
    private javax.swing.JButton bil5;
    private javax.swing.JButton bil6;
    private javax.swing.JButton bil7;
    private javax.swing.JButton bil8;
    private javax.swing.JButton bil9;
    private javax.swing.JTextField display;
    private javax.swing.JButton hapus1;
    private javax.swing.JButton hapus3;
    private javax.swing.JButton hasil;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kali;
    private javax.swing.JButton kurang;
    private javax.swing.JButton modulus;
    private javax.swing.JButton pangkat;
    private javax.swing.JButton plusmin;
    private javax.swing.JButton sisahasilbagi;
    private javax.swing.JButton tambah;
    private javax.swing.JButton titik;
    // End of variables declaration//GEN-END:variables
}
