/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author ASUS
 */
public class Latihan1 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    public Latihan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        bil1 = new java.awt.TextField();
        bil2 = new java.awt.TextField();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        buttonKali = new java.awt.Button();
        buttonBagi = new java.awt.Button();
        buttonTambah = new java.awt.Button();
        buttonKurang = new java.awt.Button();
        buttonSisaHasilBagi = new java.awt.Button();
        hasil = new java.awt.TextField();
        label4 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(580, 486));
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        label1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        label1.setName("Kalkulator Sederhana"); // NOI18N
        label1.setText("Kalkulator Sederhana");
        jPanel2.add(label1);
        label1.setBounds(180, 50, 240, 47);
        jPanel2.add(bil1);
        bil1.setBounds(130, 120, 170, 20);
        jPanel2.add(bil2);
        bil2.setBounds(130, 170, 170, 20);

        label2.setText("Bilangan 1");
        jPanel2.add(label2);
        label2.setBounds(20, 120, 100, 20);

        label3.setText("Bilangan 2");
        jPanel2.add(label3);
        label3.setBounds(20, 170, 100, 20);

        buttonKali.setLabel("X");
        buttonKali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKaliActionPerformed(evt);
            }
        });
        jPanel2.add(buttonKali);
        buttonKali.setBounds(130, 230, 23, 24);

        buttonBagi.setLabel("/");
        buttonBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBagiActionPerformed(evt);
            }
        });
        jPanel2.add(buttonBagi);
        buttonBagi.setBounds(200, 230, 19, 24);

        buttonTambah.setLabel("+");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });
        jPanel2.add(buttonTambah);
        buttonTambah.setBounds(270, 230, 23, 24);

        buttonKurang.setLabel("-");
        buttonKurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKurangActionPerformed(evt);
            }
        });
        jPanel2.add(buttonKurang);
        buttonKurang.setBounds(350, 230, 20, 24);

        buttonSisaHasilBagi.setLabel("%");
        buttonSisaHasilBagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSisaHasilBagiActionPerformed(evt);
            }
        });
        jPanel2.add(buttonSisaHasilBagi);
        buttonSisaHasilBagi.setBounds(430, 230, 27, 24);

        hasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilActionPerformed(evt);
            }
        });
        jPanel2.add(hasil);
        hasil.setBounds(130, 330, 200, 50);

        label4.setText("        Hasil");
        jPanel2.add(label4);
        label4.setBounds(0, 330, 120, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 580, 480);

        setSize(new java.awt.Dimension(596, 511));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSisaHasilBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSisaHasilBagiActionPerformed
int bilangan1=Integer.parseInt(bil1.getText());
        int bilangan2=Integer.parseInt(bil2.getText());
        int sembarang = bilangan1%bilangan2;
        
        hasil.setText(String.valueOf(sembarang));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSisaHasilBagiActionPerformed

    private void buttonKaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKaliActionPerformed
        // TODO add your handling code here:
        int bilangan1=Integer.parseInt(bil1.getText());
        int bilangan2=Integer.parseInt(bil2.getText());
        int sembarang = bilangan1*bilangan2;
        
        hasil.setText(String.valueOf(sembarang));
    }//GEN-LAST:event_buttonKaliActionPerformed

    private void buttonBagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBagiActionPerformed
       int bilangan1=Integer.parseInt(bil1.getText());
        int bilangan2=Integer.parseInt(bil2.getText());
        double sembarang = bilangan1/bilangan2;
        
        hasil.setText(String.valueOf(sembarang));
    }//GEN-LAST:event_buttonBagiActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
int bilangan1=Integer.parseInt(bil1.getText());
        int bilangan2=Integer.parseInt(bil2.getText());
        int sembarang = bilangan1+bilangan2;
        
        hasil.setText(String.valueOf(sembarang));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonKurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKurangActionPerformed
int bilangan1=Integer.parseInt(bil1.getText());
        int bilangan2=Integer.parseInt(bil2.getText());
        int sembarang = bilangan1-bilangan2;
        
        hasil.setText(String.valueOf(sembarang));        // TODO add your handling code here:
    }//GEN-LAST:event_buttonKurangActionPerformed

    private void hasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField bil1;
    private java.awt.TextField bil2;
    private java.awt.Button buttonBagi;
    private java.awt.Button buttonKali;
    private java.awt.Button buttonKurang;
    private java.awt.Button buttonSisaHasilBagi;
    private java.awt.Button buttonTambah;
    private java.awt.TextField hasil;
    private javax.swing.JPanel jPanel2;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration//GEN-END:variables
}
