/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagui;

/**
 *
 * @author ASUS
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pilihanjurusan = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Number = new javax.swing.JTextField();
        Jurusan1 = new javax.swing.JRadioButton();
        Jurusan2 = new javax.swing.JRadioButton();
        cbProgramming = new javax.swing.JCheckBox();
        cbAnimator = new javax.swing.JCheckBox();
        cbDesigner = new javax.swing.JCheckBox();
        cbVideoEditing = new javax.swing.JCheckBox();
        buttonSubmit = new javax.swing.JButton();
        buttonRemove = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        hasil = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(51, 102, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIODATA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 0, 160, 100);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(77, 90, 60, 14);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(80, 130, 60, 14);

        jLabel4.setText("Jurusan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 170, 70, 14);

        jLabel5.setText("Hobi");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 210, 50, 14);

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        getContentPane().add(Name);
        Name.setBounds(150, 90, 260, 30);
        getContentPane().add(Number);
        Number.setBounds(150, 130, 260, 30);

        pilihanjurusan.add(Jurusan1);
        Jurusan1.setText("RPL");
        getContentPane().add(Jurusan1);
        Jurusan1.setBounds(150, 170, 70, 23);

        pilihanjurusan.add(Jurusan2);
        Jurusan2.setText("TKJ");
        getContentPane().add(Jurusan2);
        Jurusan2.setBounds(290, 170, 90, 23);

        cbProgramming.setText("Programming");
        getContentPane().add(cbProgramming);
        cbProgramming.setBounds(150, 210, 100, 23);

        cbAnimator.setText("Animator");
        getContentPane().add(cbAnimator);
        cbAnimator.setBounds(290, 210, 110, 23);

        cbDesigner.setText("Designer");
        getContentPane().add(cbDesigner);
        cbDesigner.setBounds(150, 240, 110, 23);

        cbVideoEditing.setText("Video Editing");
        getContentPane().add(cbVideoEditing);
        cbVideoEditing.setBounds(290, 240, 120, 23);

        buttonSubmit.setText("Submit");
        buttonSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSubmitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSubmit);
        buttonSubmit.setBounds(150, 290, 70, 30);

        buttonRemove.setText("Remove");
        buttonRemove.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(buttonRemove);
        buttonRemove.setBounds(260, 290, 80, 30);

        buttonExit.setText("Exit");
        buttonExit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonExit);
        buttonExit.setBounds(380, 290, 70, 30);

        hasil.setColumns(20);
        hasil.setRows(5);
        jScrollPane1.setViewportView(hasil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(146, 350, 270, 130);

        jLabel7.setIcon(new javax.swing.ImageIcon("E:\\Tugas Sekolah\\desain flora 2.JPG")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-90, 0, 700, 490);

        jLabel6.setText("Hasil");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 350, 22, 14);

        setBounds(0, 0, 618, 526);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
    dispose();
        System.exit(1);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSubmitActionPerformed
        // TODO add your handling code here:
        String nama = Name.getText();
        String absen=Number.getText();
        String juruusan;
        String hobi="";
        
//untuk pilihan jurursan
        if (Jurusan1.isSelected())
            juruusan="RPL";
        else if(Jurusan2.isSelected())
            juruusan ="TKJ";
        else 
             juruusan=" ";
        
        //untuk checkbox
        if (cbAnimator.isSelected())
            hobi+=cbAnimator.getText()+", ";
       if (cbDesigner.isSelected())
            hobi+=cbDesigner.getText()+", ";
        if (cbProgramming.isSelected())
            hobi+=cbProgramming.getText()+", ";
         if (cbVideoEditing.isSelected())
            hobi+=cbVideoEditing.getText()+", ";
         
         //untuk hasil
         hasil.setText(" Nama anda : " +nama+"\n Absen anda : " 
                 +absen+"\n Jurusan anda : " +juruusan+ "\n Hobi anda : " +hobi);
         
    }//GEN-LAST:event_buttonSubmitActionPerformed

    private void buttonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRemoveActionPerformed
        // TODO add your handling code here:
        Name.setText("");
        Number.setText("");
        cbProgramming.setSelected(false);
        cbDesigner.setSelected(false);
        cbAnimator.setSelected(false);
        cbVideoEditing.setSelected(false);
        pilihanjurusan.clearSelection();
        hasil.setText("");
       
    }//GEN-LAST:event_buttonRemoveActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Jurusan1;
    private javax.swing.JRadioButton Jurusan2;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Number;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonRemove;
    private javax.swing.JButton buttonSubmit;
    private javax.swing.JCheckBox cbAnimator;
    private javax.swing.JCheckBox cbDesigner;
    private javax.swing.JCheckBox cbProgramming;
    private javax.swing.JCheckBox cbVideoEditing;
    private javax.swing.JTextArea hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup pilihanjurusan;
    // End of variables declaration//GEN-END:variables
}
